name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world! The workflow is triggering."
