spring:
  application:
    name: journalApp
  data:
    mongodb:
      uri: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /journal