spring:
#      url: redis-cli -u redis://default:hmSX3mbVZGh7Eh3qPnhUEHWHDeCQN6VX@redis-10818.c305.ap-south-1-1.ec2.redns.redis-cloud.com:10818
#    host: localhost
#    port: 6379

  application:
    name: journalApp
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  kafka:
#    bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: weekly-sentiment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: net.engineeringdigest.journalApp.model
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxx' password='XXXX';
#      session:
#        timeout:
#          ms: 45000


server:
  port: 8080
  servlet:
    context-path: /journal




#spring:
#  profiles:
#    active: dev

#logging:
#  level:
#    net:
#      LaabhGupta:
#        journalApp: DEBUG