spring:
  application:
    name: journalApp
  data:
    mongodb:
      uri: mongodb+srv://laabhgupta:Laabh%402604@cluster0.siyjcjz.mongodb.net/YOUR_DATABASE_NAME?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /journal