spring:
  redis:
    uri : ${REDIS_CLOUD}
#    host: localhost
#    port: 6379
  application:
    name: journalApp
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

#server:
#  port: 8080
#  servlet:
#    context-path: /journal
# Keep other non-sensitive properties as they are